GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWljaGFlbCBTY290dCIsImlhdCI6MTcwNzc0NDkyNiwiZXhwIjoxNzA3NzQ0OTUxfQ.OeTnSainVL90bIK14OcQzYDeQkmd8C9ESEkxslZvHYY

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWljaGFlbCBTY290dCIsImlhdCI6MTcwNzc0NDk4NX0.lfkdGR55zkYimMkovSWeTPa4uIjoNyGUgVwH0zJ8wsw"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Michael Scott"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWljaGFlbCBTY290dCIsImlhdCI6MTcwNzc0NDg3NX0.VbMbiCsQkarAzcQ-sms812eAqNjHuJqRsm0D8L35o0s"
}